CREATE TABLE confederations
(
    id   BIGINT generated by default as identity (start with 1),
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE countries
(
    id                       BIGINT generated by default as identity (start with 1),
    name                     VARCHAR(50) NOT NULL UNIQUE,
    population               INTEGER     NOT NULL,
    ocde                     BOOLEAN     NOT NULL,
    capital                  VARCHAR(50) NOT NULL UNIQUE,
    united_nations_admission DATE,
    confederation_id         BIGINT,
    PRIMARY KEY (id)
);

ALTER TABLE countries ADD FOREIGN KEY (confederation_id) REFERENCES confederations (id);